# Generated by Django 4.1.7 on 2025-04-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SousThematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lien', models.URLField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_thematiques', to='analytics.thematique')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
