# Generated by Django 4.1.7 on 2025-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousthematique',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
