# Generated by Django 5.2 on 2025-04-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_sousthematique_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('bar', 'Colonnes'), ('line', 'Lignes'), ('pie', 'Camembert')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('sous_thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphiques', to='analytics.sousthematique')),
            ],
        ),
        migrations.CreateModel(
            name='SerieDonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categories', models.JSONField()),
                ('valeurs', models.JSONField()),
                ('graphique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='analytics.graphique')),
            ],
        ),
    ]
