# Generated by Django 4.1.7 on 2025-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_graphique_seriedonnee'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphique',
            name='titre_abscisse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphique',
            name='titre_ordonnée',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seriedonnee',
            name='couleur',
            field=models.CharField(default='#3e95cd', max_length=7),
        ),
    ]
