# Generated by Django 4.1.7 on 2025-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_graphique_titre_abscisse_graphique_titre_ordonnée_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriedonnee',
            name='couleurs_camembert',
            field=models.JSONField(blank=True, help_text='Palette de couleurs utilisée uniquement pour les graphiques camemberts', null=True),
        ),
    ]
