# Generated by Django 5.2 on 2025-04-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_seriedonnee_couleurs_camembert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriedonnee',
            name='couleurs_camembert',
        ),
    ]
