# Generated by Django 5.2 on 2025-04-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_remove_seriedonnee_couleurs_camembert'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriedonnee',
            name='couleurs_camembert',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
