# Generated by Django 4.1.7 on 2025-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_seriedonnee_couleurs_camembert'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphique',
            name='colonne_categorie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
