# Generated by Django 4.1.7 on 2025-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_graphique_colonne_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphique',
            name='fichier_excel',
            field=models.FileField(blank=True, null=True, upload_to='excels/'),
        ),
    ]
