# Generated by Django 5.2 on 2025-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_graphique_fichier_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphique',
            name='height',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='graphique',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphique',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphique',
            name='width',
            field=models.IntegerField(default=6),
        ),
    ]
