# Generated by Django 4.1.7 on 2025-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_graphique_height_graphique_pos_x_graphique_pos_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphique',
            name='type',
            field=models.CharField(choices=[('bar', 'Colonnes'), ('line', 'Lignes'), ('pie', 'Camembert'), ('doughnut', 'Doughnut')], max_length=50),
        ),
    ]
