# Generated by Django 5.2 on 2025-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_graphique_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphique',
            name='afficher_legende',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seriedonnee',
            name='afficher_labels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seriedonnee',
            name='ajouter_pourcentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seriedonnee',
            name='y_axis',
            field=models.CharField(choices=[('left', 'Axe Gauche'), ('right', 'Axe Droit')], default='left', max_length=5),
        ),
    ]
